create table if not exists public.signups (
  id bigint generated by default as identity primary key,
  lead_id text unique,
  created_at timestamptz default now(),
  type text,
  name text,
  email text,
  plan text,
  source text,
  details jsonb default '{}'::jsonb
);

alter table public.signups enable row level security;

create policy "service role can manage signups"
on public.signups
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text,
  plan text,
  status text,
  stripe_customer_id text,
  stripe_subscription_id text unique,
  current_period_end timestamptz,
  trial_end timestamptz,
  cancel_at_period_end boolean default false,
  updated_at timestamptz default now()
);

alter table public.subscriptions enable row level security;

create policy "service role can manage subscriptions"
on public.subscriptions
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create table if not exists public.attempts (
  id text primary key,
  created_at timestamptz default now(),
  user_id text,
  user_name text,
  email text,
  scenario_id text,
  mode text,
  market text,
  pattern text,
  answer text,
  correct boolean,
  correct_answer text,
  confidence text,
  xp_earned integer default 0,
  time_to_answer numeric,
  difficulty text,
  session text,
  source text,
  metadata jsonb default '{}'::jsonb
);

alter table public.attempts enable row level security;

drop policy if exists "service role can manage attempts" on public.attempts;

create policy "service role can manage attempts"
on public.attempts
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create index if not exists attempts_scenario_idx on public.attempts (scenario_id);
create index if not exists attempts_created_idx on public.attempts (created_at);
create index if not exists attempts_user_idx on public.attempts (user_id);
