create table if not exists public.signups (
  id bigint generated by default as identity primary key,
  lead_id text unique,
  created_at timestamptz default now(),
  type text,
  name text,
  email text,
  plan text,
  source text,
  details jsonb default '{}'::jsonb
);

alter table public.signups enable row level security;

create policy "service role can manage signups"
on public.signups
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text,
  plan text,
  status text,
  stripe_customer_id text,
  stripe_subscription_id text unique,
  current_period_end timestamptz,
  trial_end timestamptz,
  cancel_at_period_end boolean default false,
  updated_at timestamptz default now()
);

alter table public.subscriptions enable row level security;

create policy "service role can manage subscriptions"
on public.subscriptions
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
